### ISSUE TITLE
client.GenerateSurveyQuery with empty (but not nil) PublishSignatureBytes panic

### ISSUE THREAD

**Issue by tharvik** [ldsec/drynx#25]
```go
client.GenerateSurveyQuery(
    [...]
    []*[]drynx_lib.PublishSignatureBytes{},
    [...]
```
panic with
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/ldsec/drynx/services.(*API).GenerateSurveyQuery(0xc000098ec0, 0xc000098e80, 0xc000098e80, 0xc000a21170, 0xc000a211a0, 0xc00023ed10, 0xf, 0xc00023ed78, 0x8, 0x1, ...)
	/home/tharvik/c4dt/drynx/services/api.go:63 +0x401
main.surveyRun(0xc00024e2c0, 0x0, 0xc0001c7220)
	/home/tharvik/c4dt/drynx/cmd/client/survey.go:95 +0x776
github.com/urfave/cli.HandleAction(0xbb2740, 0xcebb70, 0xc00024e2c0, 0xc00024e2c0, 0x0)
	/home/tharvik/.go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:523 +0xbe
github.com/urfave/cli.Command.Run(0xcb943c, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/tharvik/.go/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:174 +0x51c
github.com/urfave/cli.(*App).RunAsSubcommand(0xc00024a1c0, 0xc00024e000, 0x0, 0x0)
	/home/tharvik/.go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:404 +0x869
github.com/urfave/cli.Command.startApp(0xcbb7cd, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcc46d7, 0x12, 0x0, ...)
	/home/tharvik/.go/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:329 +0x845
github.com/urfave/cli.Command.Run(0xcbb7cd, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xcc46d7, 0x12, 0x0, ...)
	/home/tharvik/.go/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:102 +0x9ca
github.com/urfave/cli.(*App).Run(0xc00024a000, 0xc0000b0150, 0x3, 0x3, 0x0, 0x0)
	/home/tharvik/.go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:276 +0x718
main.main()
	/home/tharvik/c4dt/drynx/cmd/client/main.go:59 +0x2ab
```

**Comment by JoaoAndreSa** [comment]
Ok I know what is the issue. The problem is that there is a lot error handling which we haven't done.  :( In this case we should add a length check on the object drynx_lib.PublishSignatureBytes. The size of this array should match with the nbrOfOutputs so if this is nil or empty the system is not expected to generate range proofs. So if 'range proofs' is active and this is drynx_lib.PublishSignatureBytes is empty or nil it should not run.  I am adding a pull request to fix this.

**Comment by tharvik** [comment]
> Ok I know what is the issue. The problem is that there is a lot error handling which we haven't done. :(

That's totaly normal, academia is feature oriented and I'm the stability guy; I've reported some I found in here, I'm thinking of fixing theses along the way, it was more for remembering me to look into it :)
The ones I'm unable to help/fix are #5 and #17 (and maybe #19).
